<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <style>
        body {
            font-family: 'Helvetica', 'Arial', sans-serif;
            margin: 0;
            padding: 20px;
            color: #333;
        }
        .header {
            text-align: center;
            margin-bottom: 20px;
            padding-bottom: 10px;
            border-bottom: 1px solid #eee;
        }
        .header h3 {
            margin: 0;
            font-size: 18px;
            color: #444;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            font-size: 10px;
            table-layout: fixed;
            word-wrap: break-word;
        }
        th, td {
            border: 1px solid #ddd;
            padding: 6px 8px;
            text-align: left;
            line-height: 1.4;
        }
        th {
            background-color: #f8f8f8;
            font-weight: 600;
            color: #444;
        }
        tr:nth-child(even) {
            background-color: #f9f9f9;
        }
        .footer {
            text-align: center;
            margin-top: 20px;
            padding-top: 10px;
            border-top: 1px solid #eee;
            font-size: 9px;
            color: #777;
        }
    </style>
</head>
<body>
    <div class="header">
        <h3>Visitor History Export</h3>
    </div>

    <table>
        <thead>
            <tr>
                <th style="width: 12%">Name</th>
                <th style="width: 12%">Company</th>
                <th style="width: 10%">Purpose</th>
                <th style="width: 7%">In</th>
                <th style="width: 7%">Out</th>
                <th style="width: 12%">Host Name</th>
                <th style="width: 10%">Floor/Venue</th>
                <th style="width: 8%">Phone</th>
                <th style="width: 12%">Email</th>
                <th style="width: 8%">Visit Date</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($data as $row)
                <tr>
                    <td>{{ $row['Name'] }}</td>
                    <td>{{ $row['Company'] }}</td>
                    <td>{{ $row['Visit Purpose'] }}</td>
                    <td>{{ $row['In'] }}</td>
                    <td>{{ $row['Out'] }}</td>
                    <td>{{ $row['Host Name'] }}</td>
                    <td>{{ $row['Floor/Venue'] }}</td>
                    <td>{{ $row['Phone'] }}</td>
                    <td>{{ $row['Email'] }}</td>
                    <td>{{ $row['Visit Date'] }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        Generated by AATC VMS on {{ date('Y-m-d H:i') }} | Confidential
    </div>
</body>
</html>
